apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: azure-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      organization: Live-Beach-Network
      labels:
        - arc-gh-runner
      env:
      - name: RUNNER_FEATURE_FLAG_EPHEMERAL
        value: "true"

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: azure-runners-deployment-autoscaler
  namespace: actions-runner-system
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    name: azure-gh-runner
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.25'
    scaleUpFactor: '2'
    scaleDownFactor: '0.5'